### ISSUE TITLE
How do we implement OneUI like lazy column?

### ISSUE THREAD

**Issue by abdullateefsherani07** [TrainerSnow/oneui-compose#68]

**Comment by SimonBumiller** [comment]
Hi, I'm not sure what you mean. You can still use the `LazyColumn` composable and use OneUI components inside of it. Do you have a screenshot of what exactly you mean?

**Comment by abdullateefsherani07** [comment]
> Hi, I'm not sure what you mean. You can still use the `LazyColumn` composable and use OneUI components inside of it. Do you have a screenshot of what exactly you mean?

I mean how do we actually use ItemScroll composable. Can't we pass just a list to it. If not what's the actual use of it

**Comment by SimonBumiller** [comment]
Oh i see, `ItemScroll` is not related to `LazyList`.  Its used to do animations like these:

https://github.com/TrainerSnow/oneui-compose/assets/81151019/3d2b7ea3-d2da-46ea-9b61-c0277827cb0c

If you want to know how you can use `ItemScroll`, you could take a look at the `NumberPicker` composable in `org.oneui.compose.picker`.

**Comment by abdullateefsherani07** [comment]
> > Hi, I'm not sure what you mean. You can still use the `LazyColumn` composable and use OneUI components inside of it. Do you have a screenshot of what exactly you mean?
> 
> I mean how do we actually use ItemScroll composable. Can't we pass just a list to it. If not what's the actual use of it

One more thing. You mentioned spinner in OneUI sample app in widgets. But I couldn't find it in library

**Comment by SimonBumiller** [comment]
I don't think i ever released a sample app for this project (correct me if i'm wrong), could you share where you downloaded that? You may be confusing it with one of the sample apps for the XML OneUI library.
