### ISSUE TITLE
How to use Collapsing toolbar layout with scaffold 

### ISSUE THREAD

**Issue by abdullateefsherani07** [TrainerSnow/oneui-compose#69]
I am using Scaffold with app bar and navigation bar. I was able to replace material navigation bar with OneUI bottom navigation bar and it works fine. But when I replace material app bar with OneUI CollapsingToolbarLayout it doesn't work. toolbar is expanded doesn't collapse on scroll

**Comment by SimonBumiller** [comment]
Could you show me how you used it, e.g. via a gist?
